name: Build and push personal site to GH pages
run-name: ${{ github.actor }} is pushing the site!
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: |
          npm install
          npm run build:public
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      