name: Build and push personal site to GH pages
run-name: ${{ github.actor }} deploying site

on:
  repository_dispatch: 
    types: [private-content-update]
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN_PRIVATE_CONTENT }}
          submodules: true
          # We need to fetch all history for the auto-commit action to work
          fetch-depth: 0
      - name: Update Submodule to Latest
        run: |
          git submodule update --remote --merge
      - name: Commit Submodule Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update private content submodule commit hash [skip ci]"
          file_pattern: src/private-content
      - name: Build
        run: |
          npm install
          npm run build
          cp build/index.html build/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4